apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # use cmd: echo -n {your_text} | base64 to encode
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLW9eaW5zdGFsbHFxPXE3X2UrY0BeQDdfZzB1a2k4Ni15Z3R1c3JzOD1jaHJ2MC1nQGcreng=
  DB_USER: dXNlcg==
  DB_PASS: dXNlcg==