apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: k8spracdjango  # Updated to match the label in Deployment
  ports:
    - protocol: TCP
      port: 8001  # Make sure this matches the containerPort in your Deployment
      targetPort: 8001  # Make sure this matches the containerPort in your Deployment
