apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldb
          image: harshdevsingh1992/k8spracmysqldb:v1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_PASS
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_PASS
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldb
            - name: mysql-secrets
              mountPath: "/etc/mysql-secrets"
              readOnly: true
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-secrets
          secret:
            secretName: mysql-secrets
